### ISSUE TITLE
Is it possible to disable SSL verification for localhost?

### ISSUE THREAD

**Issue by arisliang** [guillp/requests_oauth2client#10]
- `requests_oauth2client` version: 1.1.0
- Python version: 3.9
- Operating System: windows 10

### Description

>requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=7060): Max retries exceeded with url: /connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

For localhost, is it possible to disable the ssl verification? For requests, this can be done by setting `verify=False` in requests.get. Is it possible for `client.token_request` here?

### What I Did

```
client = OAuth2Client(token_endpoint='https://localhost:7060/connect/token',
                          auth=(client_id, client_secret))
    data = dict(grant_type=grant_type,
                scope=scope,
                username=username,
                password=password)
    token = client.token_request(data)
```

**Comment by guillp** [comment]
Yes you can: use the parameter `requests_kwargs` to `token_requests`:
```python
client = OAuth2Client(token_endpoint='https://localhost:7060/connect/token',
                          auth=(client_id, client_secret))
data = dict(grant_type=grant_type,
            scope=scope,
            username=username,
            password=password)
token = client.token_request(data, requests_kwargs={"verify": False})
```

alternatively you can pass a custom session to OAuth2Client:

```python
session = requests.Session()
session.verify = False

client = OAuth2Client(
    token_endpoint='https://localhost:7060/connect/token',
    auth=(client_id, client_secret),
    session=session
)
data = dict(grant_type=grant_type,
            scope=scope,
            username=username,
            password=password)
token = client.token_request(data)
```

**Comment by guillp** [comment]
I close this issue, but feel free to comment if you need more information.
