### ISSUE TITLE
(feature) Resource owner password grant auth handler

### ISSUE THREAD

**Issue by amacleay-cohere** [guillp/requests_oauth2client#19]
- `requests_oauth2client` version: @ main
- Python version: 3.11.4
- Operating System: linux

### Description

There is an auth handler for:
* [Authorization code grant](https://github.com/guillp/requests_oauth2client/blob/1d4b3ed6ffb8d794992e6ebba4fec0ca310e4eaf/requests_oauth2client/auth.py#L200)
* [Client credentials grant](https://github.com/guillp/requests_oauth2client/blob/1d4b3ed6ffb8d794992e6ebba4fec0ca310e4eaf/requests_oauth2client/auth.py#L91)
* [Device code grant](https://github.com/guillp/requests_oauth2client/blob/1d4b3ed6ffb8d794992e6ebba4fec0ca310e4eaf/requests_oauth2client/auth.py#L252)

It would be nice if there were a similar handler for [resource owner password grant](https://github.com/guillp/requests_oauth2client/blob/1d4b3ed6ffb8d794992e6ebba4fec0ca310e4eaf/requests_oauth2client/client.py#L551)

### What I Did

A possible implementation might look like (loosely, untested)

```python
class OAuth2ResourceOwnerPasswordAuth(BearerAuth):
    """An auth handler for Resource Owner Password Credentials grant.

    Based very closely on the OAuth2ClientCredentialsAuth handler.
    The only difference is that token renewal uses a different method, and
    we add more leeway to token expiration check."""

    def __init__(self, client: "OAuth2Client", **token_kwargs):
        super().__init__(None)
        self.client = client
        self.token_kwargs = token_kwargs

    def __call__(self, request: requests.PreparedRequest) -> requests.PreparedRequest:
        token = self.token
        if token is None or token.is_expired():
            self.renew_token()
        return super().__call__(request)

    def renew_token(self) -> None:
        self.token = self.client.resource_owner_password(
            username=self.token_kwargs["username"],
            password=self.token_kwargs["password"],
            **self.token_kwargs,
        )
```

**Comment by guillp** [comment]
Will implement after the "expiration leeway" changes are sorted out, since this will also use that feature.
