### ISSUE TITLE
Missing dependency `attrs`?

### ISSUE THREAD

**Issue by zaraken** [guillp/requests_oauth2client#50]
- `requests_oauth2client` version: 1.5.0
- Python version: 3.11.7
- Operating System: Ubuntu 22.04

### Description

Running
```
pip install requests-oauth2client
python -c 'from requests_oauth2client import OAuth2Client, OAuth2ClientCredentialsAuth'
leads to 

```... /python3.11/site-packages/requests_oauth2client/api_client.py", line 10, in <module>
    from attrs import field, frozen
ModuleNotFoundError: No module named 'attrs'
```

Should it be added as a dependency ?
Sorry, not familiar with the project. Could check later, but have to do a deployment first

**Comment by guillp** [comment]
fixed in v1.5.1
