### ISSUE TITLE
Cannot create oauth2 client if token-endpoint has custom port

### ISSUE THREAD

**Issue by dnj12345** [guillp/requests_oauth2client#55]
- `requests_oauth2client` version: 1.5.1
- Python version: 3.9.18
- Operating System: Linux Redhat ubi9 container

### Description

Getting an error when I try to create an OAuth2Client client with client_credentials grant

### What I Did
It works correctly, if I remove `:8443` from my token endpoint url. The documentation does not mention any such constraints. Googling did not provide an advice either. Any advice is appreciated. 

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/ubi-user/.local/lib/python3.9/site-packages/requests_oauth2client/client.py", line 274, in validate_endpoint_uri
    return validate_endpoint_uri(uri)
  File "/home/ubi-user/.local/lib/python3.9/site-packages/requests_oauth2client/utils.py", line 70, in validate_endpoint_uri
    raise ValueError(", ".join(msg))
ValueError: no custom port number allowed

....

    oauth2client = OAuth2Client(token_endpoint=self.auth_url,
  File "/home/ubi-user/.local/lib/python3.9/site-packages/requests_oauth2client/client.py", line 230, in __init__
    self.__attrs_init__(
  File "<attrs generated init requests_oauth2client.client.OAuth2Client>", line 32, in __attrs_init__
    __attr_validator_token_endpoint(self, __attr_token_endpoint, self.token_endpoint)
  File "/home/ubi-user/.local/lib/python3.9/site-packages/requests_oauth2client/client.py", line 277, in validate_endpoint_uri
    raise ValueError(msg) from exc
ValueError: Invalid value 'https://auth.mydomain.test-dev.cloud:8843/auth/realms/user/protocol/openid-connect/token' for 'token_endpoint': no custom port number allowed

```

**Comment by guillp** [comment]
By default, endpoint urls are validated to check if they are "sane". Using a custom port is usually a sign that you are using either an "in-development" or a "hacked" AS, but it is difficult to automatically guess which case applies.

You can disable this validation by passing `testing=True` when initializing your OAuth2Client:

```python
from requests_oauth2client import OAuth2Client

client = OAuth2Client(
    token_endpoint="https://auth.mydomain.test-dev.cloud:8843/auth/realms/user/protocol/openid-connect/token",
    client_id="myclientid",
    testing=True, # disable endpoint validation
)

# OR, if you use a discovery endpoint
client = OAuth2Client.from_discovery_endpoint(
    iss="https://https://auth.mydomain.test-dev.cloud:8843",
    testing=True,
)
```

**Comment by dnj12345** [comment]
Awesome! Thanks @guillp. Exactly what I needed. 

One request though. I did look for this option but couldn't find it in te docs. Adding it to the docs would help. Also, there may be situations where folks run the server on a custom port. For those cases, it'd be good to add an option allow_custom_port or some option like. The `testing` option seems a little unofficial. Thank you.

**Comment by guillp** [comment]
@dnj12345 : the full API documentation is available here:
https://guillp.github.io/requests_oauth2client/api/#requests_oauth2client.client.OAuth2Client
and the `testing` parameter is described there :)

But I agree that documentation needs some review and polish... I would gladly accept any feedback, corrections, requests for specific topics or even better, PR on the docs :D

**Comment by fgreinacher** [comment]
> You can disable this validation by passing testing=True when initializing your OAuth2Client:

@guillp Would you be open to allow disabling checks more selectively? We don't want the port check, but the other ones do make sense. Happy to send a PR if you agree.

**Comment by guillp** [comment]
Why not, but you would mind elaborating on you use-case first ? Why is your AS using a custom port ? And is the port number included in your AS `issuer` ?

**Comment by fgreinacher** [comment]
Sorry for the late response @guillp, I was busy and on vacation.

Well, we need to interact with an existing internal service that does not really follow best practices, but is out of our control 😢 The access token is not even a JWT 😬

**Comment by guillp** [comment]
No worries, same here about being busy and on holidays ;)

I re-read all the specs I could, and did not find any mention of forbidding a custom port number. So I would be tempted to remove that check in `requests_oauth2client`, or to allow bypassing it selectively.
One question: are you initializing your client using a well-known discovery url with `OAuth2Client.from_discovery_endpoint`, or by passing all uris manually?

**Comment by fgreinacher** [comment]
> I re-read all the specs I could, and did not find any mention of forbidding a custom port number. So I would be tempted to remove that check in `requests_oauth2client`, or to allow bypassing it selectively.

I also don't see a good reason why the check should exist, except it gently pushes folks to use standard ports (which I favor strongly - but unfortunately not everyone shares that mindset :))

> One question: are you initializing your client using a well-known discovery url with `OAuth2Client.from_discovery_endpoint`, or by passing all uris manually?

We're passing the URIs directly:

```python
oauth2_client = OAuth2Client(
    token_endpoint=settings.SAP_OAUTH2_TOKEN_URL,
    auth=(
        settings.SAP_OAUTH2_CLIENT_ID,
        settings.SAP_OAUTH2_CLIENT_SECRET,
    ),
    # Disable token endpoint URL verification to allow custom port, as suggested
    # in https://github.com/guillp/requests_oauth2client/issues/55.
    testing=True,
)
```
