### ISSUE TITLE
Feature Request: Allow configuring the header access tokens go into

### ISSUE THREAD

**Issue by BrentRodhouse** [guillp/requests_oauth2client#70]
- `requests_oauth2client` version: 1.5.3
- Python version: 3.12.2
- Operating System: Ubuntu 22.04.4

### Description

My team and I have a use case where we need to send requests with the access token in a header besides the typical Authorization header (specifically, the Proxy-Authorization header). We would like the ability to specify which header the token goes into upon initialization of `BearerAuth` (or subclasses). For example:

```python
oauth2client = OAuth2Client(
    token_endpoint=...,
    client_id=...,
    client_secret=...
)

auth = OAuth2ClientCredentialsAuth(oauth2client, header="Proxy-Authorization")
```
This `auth` object would place the token in the Proxy-Authorization header instead of the Authorization header.

I'm more than willing to contribute and make a PR for this. I've been looking at the 1.5.3 code and have a pretty good idea of how I'd do it, but I saw you're working on an upcoming 1.6 that shifts some stuff around. Let me know if you're open to a change for this, and if so, what direction I should take it. Thank you!

**Comment by guillp** [comment]
Hello there!

First time I see OAuth2 used for Proxy Authorization, but it sounds like a valid use case.
I implemented a few changes to make it possible and easy in 1.6.0. This is based on a custom token class that you can configure for an OAuth2Client instance:

```python
class ProxyAuthorizationBearerToken(BearerToken):
    """Handles Proxy-Authorization"""
    AUTHORIZATION_HEADER = "Proxy-Authorization"

oauth2client = OAuth2Client(
    token_endpoint="https://as.local/token",
    client_id="client_id",
    client_secret="client_secret",
    token_class=ProxyAuthorizationBearerToken
)

auth = OAuth2ClientCredentialsAuth(oauth2client)
```

**Comment by BrentRodhouse** [comment]
Hi @guillp 
Thanks so much for implementing this! I'll download the main branch and confirm that it works for our use case and let you know.
Do you have an idea of when you plan to release 1.6.0?

**Comment by guillp** [comment]
I need to write a full list of all the breaking changes first (there are a few), and I'll also wait for your testing :)

**Comment by BrentRodhouse** [comment]
We tested out the main branch today, and it works great for our use case

**Comment by guillp** [comment]
closing now that 1.6.0 is released, allowing that use case easily.
