### ISSUE TITLE
How to view token details with ApiClient

### ISSUE THREAD

**Issue by gabrielwong1991** [guillp/requests_oauth2client#9]
Hi I followed your readme for using `Api_client` with `OAuth2AuthorizationCodeAuth()` for managing and refreshing Auth token flow.

Before I obtained token manually with `token = oauth2client.authorization_code(auth_response)` and I can view the token details.

With `Api_client` ( I believe it is a wrapper with additional function with `request.session()`). How can I view the token information like token, refresh_token, time left, scope etc?

Thanks

**Comment by guillp** [comment]
I believe that's what you are looking for:

```python
from requests_oauth2client import ApiClient, OAuth2Client, OAuth2AuthorizationCodeAuth

client = OAuth2Client("https://url.to.the/token_endpoint", auth=("your_client_id", "your_client_secret"))

# manage to obtain an authorization code, here I hardcoded it:
code = "an_az_code"

api = ApiClient("https://url.to.your.api/", auth=OAuth2AuthorizationCodeAuth(client, code))

# you need to make a first API call to trigger fetching the access token
resp = api.get("resource")

# the access token (with all associated metadata) is then available in `api.session.auth.token`. It is `None` until a token is fetched, then it is a `BearerToken`:
assert isinstance(api.session.auth.token, BearerToken)
```

In other words, if `api` is an `ApiClient` instance:
- you have access to the underlying `requests.Session` in `api.session`
- `api.session.auth` is the authentication handler
- and `api.session.auth.token` is the token retrieved by any subclass of `requests_oauth2client.BearerAuth`, including `OAuth2AuthorizationCodeAuth`.

I'm marking this ticket as closed, but feel free to reply if you need other info.


Side note: I am working improving the the Authorization Code flow related API for a next release:
- `OAuth2Client` will accept an `authorization_endpoint` and a `redirect_uri` as parameter
-  a new method `OAuth2Client.authorization_request()` will generate a properly initialized `AuthorizationRequest`
- a new method `BearerToken.validate_id_token()` will handle ID Token validation (handling decryption if needed, checking signature, checking expiration, issuer, audience, `nonce`, `at_hash`, and that `acr_values` matches the one requested, and other checks as described in https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by gabrielwong1991** [comment]
Thanks for your detailed reply Guillaume! I have another question, so my intention is to do the first step of the Authorization token flow once; that is do the `AuthorizationRequest()`, and exchange this Authorization Code for an Access Token. The purpose of doing this is to let users only need to Authorize the app once. (The grant for the app expires in 18 months but it needs to keep refreshing for access_token say every day or so...)

I would then store the `access_token`, `refresh_token`, `time_left` etc... all these pieces of information in the database. And get these parameters out when a user reuses the app. Obviously, I can do this with `BearerToken` but if the token is expired (i can check `BearerToken().is_expired()` and do the renewal manually) but is there any convenient way to automatically renew the token just like `OAuth2AuthorizationCodeAuth` does? Thanks.

**Comment by gabrielwong1991** [comment]
Found it! it is `OAuth2AccessTokenAuth`
